bundler_args: --without development
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - ruby-head
matrix:
  include:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true
script: bundle exec rake default
