bundler_args: --without development
language: ruby
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
    - rvm: 1.8.7
    - rvm: 2.0.0
rvm:
  - jruby-19mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
